site_name: VRV产品部署与维护
theme:
  name: material

nav:
- 主机审计: #null
    - 1.概述: vios/overview.md
    - 2.安装与初始化: vios/install.md
    - 3.使用与配置: vios/using.md
    - 4.问题处理: vas/question.md #到这里
    - 5.忘记密码: vios/forgetpwd.md

- 打印刻录: #完工
      - 1.概述: vios/overview.md
      - 2.安装与初始化: vios/install.md
      - 3.使用与配置: vios/using.md
      - 4.问题处理: vios/question.md
      - 5.忘记密码: vios/forgetpwd.md
      - 6.刷卡器: vios/card_reader.md
      - 7.单机版: vios/danji.md

- 终端安全: #null
    - 1.概述: vios/overview.md
    - 2.安装与初始化: vios/install.md
    - 3.使用与配置: vios/using.md
    - 4.问题处理: vios/question.md
    - 5.忘记密码: vios/forgetpwd.md

- 杀毒: #null
    - 1.概述: vios/overview.md
    - 2.安装与初始化: vios/install.md
    - 3.使用与配置: vios/using.md
    - 4.问题处理: vios/question.md
    - 5.忘记密码: vios/forgetpwd.md

- 安全套件: #null
    - 1.概述: vios/overview.md
    - 2.安装与初始化: vios/install.md
    - 3.使用与配置: vios/using.md
    - 4.问题处理: vios/question.md
    - 5.忘记密码: vios/forgetpwd.md

- Linkdood: #null
    - 1.概述: vios/overview.md
    - 2.安装与初始化: vios/install.md
    - 3.使用与配置: vios/using.md
    - 4.问题处理: vios/question.md
    - 5.忘记密码: vios/forgetpwd.md

- CEMS: #null
    - 1.概述: vios/overview.md
    - 2.安装与初始化: vios/install.md
    - 3.使用与配置: vios/using.md
    - 4.问题处理: vios/question.md
    - 5.忘记密码: vios/forgetpwd.md
